export const INSERT_TO_BOTTOM = "INSERT_TO_BOTTOM";
export const CHANGE_INDEX = "CHANGE_INDEX";
export const CHANGE_SECTION = "CHANGE_SECTION";
export const CHANGE_BACKGROUND_HIGHLIGHT_INDEX = "CHANGE_BACKGROUND_HIGHLIGHT_INDEX";

export default {
  INSERT_TO_BOTTOM,
  CHANGE_INDEX,
  CHANGE_SECTION,
  CHANGE_BACKGROUND_HIGHLIGHT_INDEX,
};
